# Generated by Django 4.0.6 on 2022-08-06 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('acquisitionDate', models.DateField()),
                ('totalAcquisitionAmount', models.IntegerField()),
                ('type', models.CharField(max_length=120)),
                ('place', models.CharField(max_length=120)),
                ('sold', models.BooleanField(default=False)),
                ('sellingPrice', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning', models.IntegerField()),
                ('month', models.CharField(max_length=120)),
                ('year', models.IntegerField()),
                ('raceDate', models.DateField()),
                ('finish', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.horse')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=120)),
                ('year', models.CharField(max_length=120)),
                ('decription', models.CharField(max_length=120)),
                ('total', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.horse')),
            ],
        ),
    ]
