# Generated by Django 4.0.6 on 2022-07-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='horseData',
            fields=[
                ('name', models.TextField(max_length=500, primary_key=True, serialize=False)),
                ('acquisitionDate', models.DateField()),
                ('totalAcquisitionAmount', models.IntegerField()),
                ('type', models.TextField(max_length=500)),
                ('place', models.TextField(max_length=500)),
                ('dispersmentClaim_Sale', models.IntegerField()),
                ('dispersmentDate', models.DateField()),
            ],
        ),
    ]
