# Generated by Django 4.0.6 on 2022-07-23 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Horse Name')),
                ('acquisitionDate', models.DateTimeField()),
                ('totalAcquisitionAmount', models.IntegerField()),
                ('type', models.CharField(max_length=120)),
                ('place', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='HorseOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning', models.IntegerField()),
                ('month', models.CharField(max_length=120)),
                ('year', models.IntegerField()),
                ('raceDate', models.DateTimeField()),
                ('finish', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.horse')),
            ],
        ),
        migrations.AddField(
            model_name='horse',
            name='horseOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.horseowner'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=120)),
                ('year', models.CharField(max_length=120)),
                ('decription', models.CharField(max_length=120)),
                ('total', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.horse')),
            ],
        ),
    ]
