# Generated by Django 4.0.6 on 2025-04-29 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='decription',
            new_name='description',
        ),
    ]
