# Generated by Django 4.0.6 on 2022-08-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='month',
        ),
        migrations.RemoveField(
            model_name='race',
            name='month',
        ),
    ]
