# Generated by Django 4.0.6 on 2022-08-07 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_expense_month_remove_race_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='year',
        ),
        migrations.RemoveField(
            model_name='race',
            name='year',
        ),
        migrations.AddField(
            model_name='expense',
            name='expenseDate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='race',
            name='raceDate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
