# Generated by Django 4.0.6 on 2022-07-24 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_alter_horse_horseowner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HorseOwner',
        ),
        migrations.RemoveField(
            model_name='horse',
            name='horseOwner',
        ),
        migrations.AddField(
            model_name='horse',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horse', to=settings.AUTH_USER_MODEL),
        ),
    ]
