# Generated by Django 4.0.6 on 2025-04-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_decription_to_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('VETERINARY', 'Veterinary Care'), ('FEED', 'Feed & Nutrition'), ('TRAINING', 'Training & Lessons'), ('BOARDING', 'Boarding & Stabling'), ('EQUIPMENT', 'Equipment & Tack'), ('FARRIER', 'Farrier & Hoof Care'), ('TRANSPORT', 'Transportation'), ('COMPETITION', 'Competition & Race Fees'), ('INSURANCE', 'Insurance'), ('OTHER', 'Other Expenses')], default='OTHER', max_length=20),
        ),
    ]
