# Generated by Django 4.0.6 on 2022-07-31 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_horse_sellingprice_horse_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='month',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='year',
        ),
        migrations.RemoveField(
            model_name='race',
            name='month',
        ),
        migrations.RemoveField(
            model_name='race',
            name='year',
        ),
        migrations.AddField(
            model_name='expense',
            name='expenseDate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
