# Generated by Django 4.0.6 on 2022-07-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_horseowner_remove_horse_horseowner_horse_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
